auth0:
  audience: ${AUTH0_AUDIENCE}

stream:
  key: ${STREAM_KEY}

groups:
  product: ${GROUP_ID}

spring:
  application:
    name: "Snippet Service"

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI}
          client-id: ${AUTH_CLIENT_ID}
          client-secret: ${AUTH_CLIENT_SECRET}

server:
  port: ${SERVER_PORT}
