name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      pull-requests: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Clean Gradle
        run: ./gradlew clean

      - name: Formatting/Linting
        run: ./gradlew ktlintCheck

      - name: Tests
        run: ./gradlew koverVerify
