name: CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  branch-protection:
    uses: group-5-ingsis/workflows/.github/workflows/main-protection.yml@main
  ci:
    uses: group-5-ingsis/workflows/.github/workflows/ci.yml@main

